### ISSUE TITLE
Errors in build from previos build remain there if current build succeeds

### ISSUE THREAD

**Issue by rajan-31** [cj1128/sublime-buildx#4]
In my build I have set => "quiet": true
So I get no output when my build succeeds.
That's what I want, but problem is that since there is no build output to overwrite, so BuildX instead of showing no output, it preserves error output from previous failed build.

How to reproduce?
- in sublime-build set => "quiet": true
- forcefully fail the build with some error (You will see errors in BuildX tab)
- make build to succeed
* here we should get empty BuildX tab, but we see previous error

What I want?
After every build build output should be updated whether it's empty or with some error.

i can give more details if needed thanks.

**Comment by cj1128** [comment]
@rajan-31 

Hi Rajan, can you tell me why do you need to set `quiet:true`?

When `quiet=false` and the build succeeds, sublime will output something like '[Finished in 40ms]' which is a helpful info IMHO. Otherwise, it's hard to know whether the building is still going or it's finished.

**Comment by rajan-31** [comment]
If I set `quiet=false` and __if there is some error in code (build fails)__
then, along with errors we get this extra output at the end,
```bash
[Finished in 790ms with exit code 1]
[shell_cmd: clang++ -fdiagnostics-color -std=c++17 -Wall -Wextra '/home/rajan/1.Prog/_CP/leetcode/split-a-string-in-balanced-strings.cpp' -o ../compiled.out && timeout 2s ./../compiled.out <../input.txt > ../output.txt]
[dir: /home/rajan/1.Prog/_CP/leetcode]
[path: /home/rajan/.gem/bin:/home/rajan/1.Portables/mongodb-5.0.5/bin:/usr/local/lib/nodejs/node-v16.13.1-linux-x64/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/bin:/usr/local/go/bin]
```

This is the reason I prefer `quiet=true`, so that I only get errors.

I know this is not a serious issue, it is just a personal preference. I just wanted to bring it to your attention.

**Comment by cj1128** [comment]
@rajan-31 I have updated the plugin to 1.3.0 and added a setting called `clear_output_when_build_starts`. It's default to `false` and you can set it to `true` to achieve the desired effect when `quiet=true`.
