### ISSUE TITLE
Option to use user theme

### ISSUE THREAD

**Issue by jaamesd** [cj1128/sublime-buildx#5]
Would it be possible for this not to override the user theme?

I tried edititing my BuildX.sublime-settings fg/bg and gutter/gutter_fg to match my spacegrey eighties theme however it seems  there's some other adjustment going on as the colors still don't match. 

It would be ideal if this package could match the user's active theme.

**Comment by cj1128** [comment]
I am not sure if it's possbiel to auto match the user's active theme and I don't have much time to investigate this now 😔.

I tried spacegrey theme with `"color_scheme": "Packages/Theme - Spacegray/base16-eighties.dark.tmTheme"`. With below config you can get a decent result.

```
    "bg": "#2d2d2d",
    "fg": "#d3d0c8",
    "gutter": "",
    "gutter_foreground": "#747369",
```

<img width="1703" alt="image" src="https://github.com/cj1128/sublime-buildx/assets/4210829/f2a2b4a3-ab87-4ec9-b5d2-419c40576d43">
